[project]
name = "ddm-dashboard"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "piepy-neuro",
]

[tool.uv.sources]
piepy-neuro = { git = "https://github.com/kaancet/piepy", rev = "big-refactor" }

[dependency-groups]
dev = [
    "nbstripout>=0.9.1",
    "pre-commit>=4.6.2",
]
